/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ARCH_AARCH64 0

#define ARCH_ARM 0

#define ARCH_PPC64LE 0

#define ARCH_X86 0

#define ARCH_X86_32 0

#define ARCH_X86_64 0

#define CONFIG_16BPC 1

#define CONFIG_8BPC 1

#define CONFIG_LOG 1

#define ENDIANNESS_BIG 0

#define HAVE_ASM 0

#define HAVE_POSIX_MEMALIGN 1

#define HAVE_UNISTD_H 1

#define PREFIX 1

#define STACK_ALIGNMENT 32

// Define default bit depth 8, but some template source files need to be redefined and compile twice, see `tmpl_16` folder
#ifndef BITDEPTH
#define BITDEPTH 8
#endif

// Fix for include issue of `itx_1d.c`, because they use `#include "itx_1d.c"` to treat it as header files
#include "common/bitdepth.h"
#include "common/intops.h"
